### ISSUE TITLE
APV Artikel 27 & regels in het kort daarover

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/wet-en-regelgeving#100]
- In lid 3 wordt aangegeven dat wanneer je jou bezig houdt met illegale zaken als ambtenaar, dat dit dan als staf wordt behandeld met je. 
- Bij de regels in het kort wordt aangegeven dat je eerst door een agent hiervoor moet worden opgepakt en dan je straf zal worden gegeven.

- Wellicht een idee om bij het verkorte gedeelte, het stukje over de agent weg te halen.

- Daarnaast zou in lid 3 de straf naar categorie 5 veranderd moeten worden, aangezien dat normaal staat voor corruptie. Nu zou dit officieel enkel een waarschuwing nog zijn.

**Comment by timfloors** [comment]
ik zal er even een pr voor maken

**Comment by timfloors** [comment]
is laatst opgelost :D
