### ISSUE TITLE
Artikel VIII-4 Niet op eerste vordering tonen van identiteitsbewijs (447e SR) (aanpassing)

### ISSUE THREAD

**Issue by wolliebolly** [Tedeapolis/wet-en-regelgeving#169]
Artikel VIII-4 Niet op eerste vordering tonen van identiteitsbewijs (447e SR) in de APV van Tedeapolis geeft aan dat er alleen een boete gegeven mag worden bij het niet geven van je identiteitsbewijs op eerste vordering. In het Nederlands Strafboek is vastgesteld dat een persoon zelfs maximaal 6 uur vastgehouden mag worden als hij zijn identiteitsbewijs niet toont. Wellicht dit ook toevoegen in de APV? Uiteraard kan het korter zijn dan 6 uur.

**Comment by Willem-Dekker** [comment]
zie justitie discord voor dit
