### ISSUE TITLE
Artikel III-11 Snelheidsovertredingen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/wet-en-regelgeving#420]
100KM/H wegen toevoegen in de APV

in de APV 100 wegen creëren zoals die bij Lombank. De flitspaal geeft daar aan dat je 100km/h mag maar volgens politie mag je er maar 80. Zo zijn er nog een aantal flitsers die dit aangeven

Op het moment bestaan er enkel 80 en 130 wegen volgens de APV.

Artikel III-11 Snelheidsovertredingen
De toegestane snelheden zijn 80KM/h en 130KM/h op de snelweg.

voorbeeld Boulevard Del Perro
![image](https://github.com/Tedeapolis/wet-en-regelgeving/assets/120292087/f519a41f-7a48-44e7-8e7b-844df6c84740)

**Comment by Jelmer55** [comment]
Lijkt me eerder dat de flitspalen moeten worden aangepast. Een 100km/h weg binnen de bebouwde kom naast Lombank is erg apart.

**Comment by ExoticaTDA** [comment]
> Lijkt me eerder dat de flitspalen moeten worden aangepast. Een 100km/h weg binnen de bebouwde kom naast Lombank is erg apart.

Is op meerdere plekken, in sandy heb je d'r bijvoorbeeld ook 1

**Comment by niekschoemaker** [comment]
Kun je doen met ene pull request.
