### ISSUE TITLE
NarcoPolis garage

### ISSUE THREAD

**Issue by AimeKoenders1** [Tedeapolis/wet-en-regelgeving#94]
ALs je voertuig despawned op het eiland met daarin drugs in de kofferbak kan je hem niet meer pakken dan komt de volgende melding te staan: https://cdn.discordapp.com/attachments/642747341765607424/815614019499065364/unknown.png
Omdat er dus drugs in de kofferbak zit kan hij niet eruit worden gehaald

**Comment by Willem-Dekker** [comment]
fixed

**Comment by Willem-Dekker** [comment]
@AimeKoenders1 dit is ook de verkeerde github
